# Generated by Django 2.2.28 on 2023-06-19 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecordsmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
